### ISSUE TITLE
Error: More than one instance of bitcore-lib found

### ISSUE THREAD

**Issue by Mambix** [Mambix/bitcore#1]
```
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
01/03/2018 18:08:33    at Object.bitcore.versionGuard (/usr/local/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12:11)
01/03/2018 18:08:33    at Object.<anonymous> (/usr/local/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:15:9)
01/03/2018 18:08:33    at Module._compile (module.js:409:26)
01/03/2018 18:08:33    at Object.Module._extensions..js (module.js:416:10)
01/03/2018 18:08:33    at Module.load (module.js:343:32)
01/03/2018 18:08:33    at Function.Module._load (module.js:300:12)
01/03/2018 18:08:33    at Module.require (module.js:353:17)
01/03/2018 18:08:33    at require (internal/module.js:12:17)
01/03/2018 18:08:33    at Object.<anonymous> (/usr/local/lib/node_modules/bitcore/node_modules/insight-api/lib/blocks.js:4:15)
01/03/2018 18:08:33    at Module._compile (module.js:409:26)
01/03/2018 18:08:36/usr/local/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12
01/03/2018 18:08:36    throw new Error(message);
```

v4.1.0.6

**Comment by Mambix** [comment]
https://github.com/bitpay/bitcore/issues/1454

**Comment by Mambix** [comment]
fixed [v4.1.0.7](https://hub.docker.com/r/mambix/bitcore/tags/)

**Comment by perezdann** [comment]
Hello i hace same issue

```
bitcore@bitcore:~$ bitcored
/home/bitcore/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/home/bitcore/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/home/bitcore/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bitcore/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/insight-api/lib/blocks.js:4:15)
    at Module._compile (module.js:409:26)
bitcore@bitcore:~$ 
```

Installing in Debian 9

Edit:
I solved adding the line
`delete global._bitcore;
`

before the line
`bitcore.version = 'v' + require('./package.json').version;
`

in file:` ~/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js
`

**Comment by Mambix** [comment]
There is actually a pretty simple solution for this.

I used:

```
RUN npm install -g bitcore@4.1.0
```

in my Dockerfile to fix this
